### ISSUE TITLE
Fixing message ".. not properly set up to resolve “/.well-known/caldav”." throws integrity check

### ISSUE THREAD

**Issue by enrgyxprt** [nextcloud/documentation#2032]
I have NC in a subfolder of the root called nextcoud.
In NC under settings and general I used to receive the message,

> Your web server is not properly set up to resolve “/.well-known/caldav”. Further information can be found in the documentation 

That documentation states,. 

> If your Nextcloud instance is installed in a subfolder called nextcloud and you’re running Apache create or edit the .htaccess file within the document root of your Web server and add the following lines:

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule ^\.well-known/host-meta /nextcloud/public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /nextcloud/public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /nextcloud/public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /nextcloud/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /nextcloud/remote.php/dav/ [R=301,L]
</IfModule>

```

The issue is now NC says, 

> There are some errors regarding your setup.
>     Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)

I believe I read that htaccess should NOT be modified,
That said, and Im only taking a stab in the dark that possibly the instructions above should advise on how to modify default-ssl.conf or similar and show ?

Hope im not missing something (may be simply an .htaccess in the empty root?)
Update, following the directions (putting .htaccess in root) still throws messages up,

> There are some warnings regarding your setup.

    Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
    Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.

**Comment by MorrisJobke** [comment]
> I believe I read that htaccess should NOT be modified,

Correct. The .htaccess should be correct if it is installed into the root folder, but as you have run this from a subfolder there is no reason to change it. You need to change or add a .htaccess file in the **root folder**. This is then not part of Nextcloud and the integrity check will not take this into account and will also not warn.

> That said, and Im only taking a stab in the dark that possibly the instructions above should advise on how to modify default-ssl.conf or similar and show ?

You could also just place another config in there for that part. It only needs to be for the root of your domain. For further help please reach out in the forums, as this here is a setup issue: https://help.nextcloud.com

**Comment by enrgyxprt** [comment]
Solved by NOT following the NC documentation
In 000-default.conf I added lines between </VirtualHost> and </IfModule>: 

Redirect 301 /.well-known/carddav /nextcloud/remote.php/dav
Redirect 301 /.well-known/caldav /nextcloud/remote.php/dav

Now original .htaccess is fine and not receiving resolving errors

**Comment by enrgyxprt** [comment]
MorrisJobke, 
Directly after posting the original message, I did exactly as suggested, created the .htaccess file in the root as mentioned in the docs, placed the original .htaccess NC had from v18 and restarted apache2 and still received the errors. At that point I deleted the .htaccess in the root and added the redirects in 000-default.conf. Worked on the first try and didnt bother seeing if other .conf files would have worked (not 100% sure of apache2 config) 
In my humble opinion, the official docs should recommend editing the .conf files, but hey what do I know...
While I may have been able to modify other .conf files, this was the first one I tried and it worked.

**Comment by MorrisJobke** [comment]
> Directly after posting the original message, I did exactly as suggested, created the .htaccess file in the root as mentioned in the docs, placed the original .htaccess NC had from v18 and restarted apache2 and still received the errors. At that point I deleted the .htaccess in the root and added the redirects in 000-default.conf. Worked on the first try and didnt bother seeing if other .conf files would have worked (not 100% sure of apache2 config)
> In my humble opinion, the official docs should recommend editing the .conf files, but hey what do I know...
> While I may have been able to modify other .conf files, this was the first one I tried and it worked.

The `.htaccess` also needs to be enabled for the root folder. Also edition 000-default.conf is one place. It highly depends on your distribution where this needs to be placed. So there is not one way to configure it. If you want you can propose an update to the documentation but the initial topic in here was clearly not the way to go, so I closed it.

**Comment by gabeyww0** [comment]
I feel like this is a red herring for a lot of us.  I've tried umpteen different ways of putting the redirects and rewrites in my Apache implementation on Ubuntu 20.04 and can go to my domain formatted like files.<mydomain>.com with a `/.well-known/caldav` suffix and it properly routes to the DAV.  Yet I still get the error on the front end Overview.  Here's my setup:

1) Hyper-V Ubuntu VM on a private IP routed to by a domain through my ISP public IP
2) Apache2
3) Nextcloud in var/www/nextcloud (as the instructions for manual install stated)
4) /etc/apache2/sites-enabled/nextcloud.conf (I deleted 000-default), with the following data:

`<VirtualHost *:80>
  DocumentRoot /var/www/nextcloud
  ServerName  files.<mydomain>.com


  <Directory /var/www/nextcloud>
    Require all granted
    AllowOverride All
    Options FollowSymLinks MultiViews

  </Directory>

  <IfModule mod_dav.c>
      Dav on
      Redirect 301 /.well-known/carddav /remote.php/dav
      Redirect 301 /.well-known/caldav /remote.php/dav
  </IfModule>

  <IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /remote.php/dav [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav [R=301,L]
  </IfModule>

</VirtualHost>

`
